# Generated by Django 5.2.9 on 2026-01-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                    ("tool", "Tool"),
                ],
                max_length=20,
            ),
        ),
    ]
