# Generated by Django 5.2.9 on 2026-01-02 05:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0003_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvidence",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_by", models.CharField(blank=True, max_length=255, null=True)),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("updated_by", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_evidences",
                        to="audits.audit",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_evidences",
                        to="audits.evidence",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("audit", "evidence")},
            },
        ),
    ]
