# Generated by Django 5.2.9 on 2026-01-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_auditevidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevidence",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Descripción del archivo",
                max_length=255,
                null=True,
            ),
        ),
    ]
