# Generated by Django 5.2.9 on 2026-01-15 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0006_audittype_audit_auditor_audit_end_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditevent",
            options={"ordering": ["occurred_at"]},
        ),
        migrations.RenameField(
            model_name="auditevent",
            old_name="event_date",
            new_name="occurred_at",
        ),
        migrations.AddField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("finding", "Finding"),
                    ("recommendation", "Recommendation"),
                    ("observation", "Observation"),
                    ("meeting", "Meeting"),
                    ("milestone", "Milestone"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("planned", "Planned"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                fields=["start_date"], name="audits_audi_start_d_f5b8d2_idx"
            ),
        ),
    ]
