# Generated by Django 5.2.9 on 2026-01-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0007_add_event_type_severity_occurred_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evidence",
            name="title",
            field=models.CharField(default="Evidencia sin título", max_length=255),
        ),
    ]
