# Generated by Django 5.2.9 on 2026-01-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0008_add_title_description_to_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="Tamaño del archivo en bytes", null=True
            ),
        ),
    ]
