"""
Django settings for auditbrain project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party
    "corsheaders",
    "rest_framework",
    "django_filters",
    "rest_framework_simplejwt",
    # Local
    "core",
    "authentication",
    "audits",
    "reports",
    "mcp",
    "ai_chat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.RequestUserMiddleware",
]

# Custom User Model
AUTH_USER_MODEL = 'authentication.CustomUser'

ROOT_URLCONF = "auditbrain.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "auditbrain.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get('POSTGRES_DB', 'auditbrain'),
        "USER": os.environ.get('POSTGRES_USER', 'auditbrain_user'),
        "PASSWORD": os.environ.get('POSTGRES_PASSWORD', 'auditbrain_password'),
        "HOST": os.environ.get('POSTGRES_HOST', 'localhost'),
        "PORT": os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# SQLite config (fallback for testing without Docker)
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

MONGO_URI = os.environ.get('MONGO_URI', 'mongodb://localhost:27017/')


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.StandardResultsSetPagination',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email configuration (development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# Ollama AI Configuration
OLLAMA_CONFIG = {
    'BASE_URL': os.environ.get('OLLAMA_URL', 'http://localhost:11434'),
    'MODEL': os.environ.get('OLLAMA_MODEL', 'qwen2.5:7b'),
    'TEMPERATURE': 0.7,
    'MAX_TOKENS': 2000,
    'ENABLE_CONTEXT': True,
    'SYSTEM_PROMPT': '''### Rol

Eres un **asistente técnico especializado en AuditBrain**.
Tu **única fuente de información del mundo real** son las herramientas del **Model Context Protocol (MCP)**.

### Reglas obligatorias (MÁXIMA PRECISIÓN)

1. **USO DE HERRAMIENTAS (PRIORIDAD #1)**
   * Tu función principal es EJECUTAR HERRAMIENTAS.
   * Si te piden datos (contar, porcentajes, listar), **ejecuta `get_audit_statistics` o `list_audits` DE INMEDIATO**.
   * No hables. Ejecuta.

2. **Respuesta en Lenguaje Natural**
   * Una vez obtenido el dato, explícalo de forma clara y amigable en español.
   * NO des solo el dato crudo. Contextualiza la respuesta para que el usuario entienda.
   * Ejemplo: "El 78% de las auditorías están completadas, lo cual es un buen índice."

3. **Cálculos y Porcentajes**
   * Obtén los totales con `get_audit_statistics`.
   * Realiza la división (parte/total * 100) tú mismo.
   * Intégralo en tu explicación.

4. **Integridad**
   * No inventes. Si no hay datos, di "No encontré información sobre eso".

5. **Silencio Técnico (CRÍTICO)**
   * **NUNCA** menciones nombres de funciones como `get_audit_statistics`, `list_audits` ni "herramientas".
   * El usuario NO sabe qué son las tools. Haz el trabajo "detrás de cámaras".
   * Tu respuesta solo debe contener la información útil y la explicación humana.

7. **Fechas**

   * “Este año” = año actual.
   * “Año pasado” = año actual − 1.

8. CÁLCULOS: Si el usuario pide una operación (suma, promedio, "X más Y"), realiza el cálculo matemático y da el resultado final.
9. PORCENTAJES: Si piden "%" o "porcentaje", usa `get_audit_statistics` para obtener el total y la parte, luego calcula: (parte / total) * 100.
10. "MIS AUDITORÍAS": Si preguntan por lo que "tienen", "mis auditorías", "assigned to me":
    * Usa el ID del USUARIO ACTUAL (si está disponible en el prompt) como filtro `auditor_id` en las herramientas.

---

### Formato recomendado de respuesta

* **Número:** `2.241 auditorías completadas`
* **Porcentaje:** `Porcentaje: 78,42%`
'''
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    os.environ.get('FRONTEND_URL', 'http://localhost:3000'),
    'http://localhost:5173',  # Vite default
    'http://127.0.0.1:5173',
]

CORS_ALLOW_CREDENTIALS = True

# Also allow all if in debug, but keep origins for safety
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
